config/routes.rb
PaymentApp::Application.routes.draw do
  
  get "items/new"

  get "payments/new"

  resources :users
  resources :items
  resources :sessions, only: [:new, :create, :destroy]
  
  root :to => "pages#home"

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/create_item', :to => 'items#new'
  match '/edit_item', :to => 'items#edit'

end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :category, :name, :price

  validates :category,  presence: true, length: { maximum: 50 }
  validates :name,  presence: true, length: { maximum: 50 }
  validates :price, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation, :remember_token
  has_secure_password

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    # format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end
# == Schema Information
#
# Table name: users
#
#  id              :integer         not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime        not null
#  updated_at      :datetime        not null
#  password_digest :string(255)
#  remember_token  :string(255)
#  admin           :boolean
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper

  # Force signout to prevent CSRF attacks
  def handle_unverified_request
    sign_out
    super
  end


  
  private

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :signed_in_user, only: [:index, :edit, :update]
  before_filter :correct_user,   only: [:edit, :update]
  before_filter :admin_user,     only: :destroy
  
  def new
  	@item = Item.new
  end

  def show
  	@item = Item.find(params[:id])
  end

  def index
  	@items = Item.all
  end

  def create
    @item = Item.new(params[:item])
    if @item.save
    flash[:success] =  "Item added success!"
      redirect_to @item
    else
      render 'new'
    end
  end

  def update
    @item = Item.find(params[:id])
    if @item.update_attributes(params[:user])
      flash[:success] = "Item updated"
      sign_in @user
      redirect_to @item
    else
      render 'edit'
    end
  end

  def destroy
    Item.find(params[:id]).destroy
    flash[:success] = "Item destroyed."
    redirect_to "/items"
  end

  private

    def admin_user
       redirect_to(root_path) unless current_user.admin?
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
		@title = "Home"
	end

	def contact
		@title = "Contact"
	end

	def about
		@title = "About"
	end

	def help
		@title = "Help"
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or "/signup"
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:index, :edit, :update]
  before_filter :correct_user,   only: [:edit, :update]
  before_filter :admin_user,     only: :destroy

  def show
    @user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      # sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      # sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end
 
  private

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	#Return a title on a per-page basis.
	def title
		base_title = "Adelaide's App"
		if @title.nil?
			base_title
		else
			"#{base_title} | #{@title}"
		end
	end

	def logo
		image_tag("logo.jpg", :alt => "Payment App", :class => "round", :style => "width:225px;height:70px")
	end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)

      cookies.permanent[:remember_token] = user.remember_token
      self.current_user = user
     
    end


    def sign_out
      self.current_user = nil
      cookies.delete(:remember_token)
    end

    def current_user=(user)
      @current_user = user
    end

    def current_user
      @current_user ||= User.find_by_remember_token(cookies[:remember_token])

    end

    def current_user?(user)
      user == current_user
    end

    def signed_in?
     !current_user.nil?
    end

    def redirect_back_or(default)
      redirect_to(session[:return_to] || default)
      session.delete(:return_to)
    end

    def store_location
      session[:return_to] = request.url
    end


end

app/helpers/users_helper.rb
module UsersHelper

	 # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/items/edit.html.erb
<% provide(:title, 'Edit Item') %>
<div class="row">

  <div class="span6 offset3">
  	<h1>Edit item</h1>
  	<p style = "color:grey;"> After you have entered item details, you can easily view and edit them.</p>
    <%= form_for(@item) do |f| %>
    <%= render 'shared/error_messagesitem' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :category %>
      <%= f.text_field :category %>

      <%= f.label :price %> 
      <%= f.text_field :price %>

      <%= f.submit "Edit item", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/items/index.html.erb
<% provide(:title, 'All Items') %>


<div class="row">

  <div class="span6 offset3">
  	<h1>Show All Items</h1>
  	<p style = "color:grey;"> List of all item showing their prices and categories, click on item name to edit.</p>

  <table>
	<tr> 
	  
		<td><b>Name &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </b></td>
		<td><b>Price &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</b></td>
		<td><b>Category</b></td>
		
	</tr>
	
		

             <% @items.each do |item| %>


              <tr>
               
          <td>
            <ul class="users">
     			    <li><%= link_to item.name, item %> </li>
            </ul>
     			</td>

     			<td>
            <ul class="users">
     			    <li> <%= item.price %> </li>
            </ul>
     			</td>

    		  <td>
            <ul class="users">
     			    <li><%= item.category %></li>
            </ul>
     			</td> 

     			
    		   
    		   <tr>
  			 <% end %>


</table>



  </div>
</div>




	  
    
   

app/views/items/new.html.erb
<% provide(:title, 'All Items') %>
<div class="row">

  <div class="span6 offset3">
  	<h1>Add new item</h1>
  	<p style = "color:grey;"> After you have entered item details, you can easily view and edit them.</p>
    <%= form_for(@item) do |f| %>
    <%= render 'shared/error_messagesitem' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :category %>
      <%= f.text_field :category %>

      <%= f.label :price %> 
      <%= f.text_field :price %>

      <%= f.submit "Create a new item", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/items/show.html.erb
<% provide(:title, 'All Items') %>

<div class="row">

  <div class="span6 offset3">
  	<h1>Show Items</h1>
  	<p style = "color:grey;"> An item showing its price and category, click on item name to edit.</p>
<table>
	<tr>
	  
		<td><b>Name&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</b></td>
		<td><b>Category&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</b></td>
		<td><b>Price&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</b></td>
	  
    </tr>
    <tr>
		<td>
		    <ul class="users">
     			<li><%= @item.name %> </li>
     		</ul>
     	</td>

     	<td>
		    <ul class="users">
     			<li><%= @item.price %></li>
     		</ul>
     	</td>

     	<td>
		    <ul class="users">
     			<li><%= @item.category %></li>
     		</ul>

     	</td>


     	<td>

		    <ul class="users">
     	    <li> <%= link_to "delete", @item, method: :delete,
                                  data: { confirm: "You sure?" } %> </li>
                              </ul>
        </td>

      
		
	</tr>
</table>

</div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="">Retail Installment Payment App</a>
    by Richard Brandt
  </small>
  <nav>
    <ul>
	  <li><%= link_to "About", about_path %></li>
	  <li><%= link_to "Contact", contact_path %></li>
	  <li><%= link_to "Home", "#{}" %></li>
	</ul>
  </nav>

</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
    	    <%= link_to "Payment Web App", "/signup", id: "logo" %>
			  <nav>
                <ul class="nav pull-right">

			      
			      
			      <% if signed_in? %>

			        <li><%= link_to "Users", users_path %></li>
			        <li><%= link_to "Register Customer", "/signup" %></li>
			      
			        <li id="fat-menu" class="dropdown">
              		<a href="#" class="dropdown-toggle" data-toggle="dropdown">
                	Items <b class="caret"></b>
              		</a>
              			<ul class="dropdown-menu">
                			<li><%= link_to "Show Items", "/items" %></li>
                			<li><%= link_to "Create Item", "/create_item" %></li>
                			<li class="divider"></li>
                			
             			 </ul>
            			</li>

            		
            		<li id="fat-menu" class="dropdown">
              		<a href="#" class="dropdown-toggle" data-toggle="dropdown">
                	Account <b class="caret"></b>
              		</a>
              			<ul class="dropdown-menu">
                			<li><%= link_to "Profile", current_user %></li>
                			<li><%= link_to "Settings", edit_user_path(current_user) %></li>
                			<li class="divider"></li>
                			<li>
                  			<%= link_to "Sign out", signout_path, method: "delete" %>
                			</li>
             			 </ul>
            			</li>
         		 <% else %>
         		    <li><%= link_to "Home", root_path %></li>
         		    <li><%= link_to "Help", help_path %></li>
            		<li><%= link_to "Sign in", signin_path %></li>
          			<% end %>
			    </ul>
			  </nav>
		</div>
	</div>
</header> 

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    	<![endif]-->

<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= title %></title>
		<%= stylesheet_link_tag    "application", media: "all" %>
    	<%= javascript_include_tag "application" %>
     	<%= csrf_meta_tags %>
     	<% render 'layouts/shim' %>
    
	</head>
	<body>
		<%= render 'layouts/header' %> 
		<div class="container">
			
			<% flash.each do |key, value| %>
              <div class="alert alert-<%= key %>"><%= value %></div>
            <% end %>
			
				<%=  yield %>


			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %> 
		</div>
	</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/help.html.erb
<h1>Pages#Help</h1>
<p>Find me in app/views/pages/help.html.erb</p>

app/views/pages/home.html.erb
<div class="row">
  <div class="span6 offset3">

  <% if !signed_in? %>
      	<h1>Sign in</h1>
        <%= form_for(:session, url: sessions_path) do |f| %>

          <%= f.label :customer_identification %>
          <%= f.text_field :email %>

          <%= f.label :password %>
          <%= f.password_field :password %>

          <%= f.submit "Sign in", class: "btn btn-large btn-primary" %>
        <% end %>
  

  <% else %>

          <div class="center hero-unit">



          <h4>Retail Installment Payment App</h4>
        <p>
          Please view all payments you made on items bought. Admin should sign in to view and update payments made by customers.
        </p>

        </div>
  <% end %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messagesitem.html.erb
<% if @item.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@item.errors.count, "error") %>.
    </div>
    <ul>
    <% @item.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_user.html.erb
<li>
  <%# gravatar_for user %>
  <%= link_to user.name, user %>

  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit Customer") %> 

<div class="row">
  <div class="span6 offset3">
    <h1>Update customer profile</h1>
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
    
  </div>
</div>

app/views/users/index.html.erb
<div class="row">

  <div class="span6 offset3">
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>
</div>
</div>

app/views/users/new.html.erb
<div class="row">

  <div class="span6 offset3">
  	<h1>Customer Registration</h1>
  	<p style = "color:grey;"> When you register a customer, they can easily verify all their installment payments.</p>
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :customer_identification %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">

  <div class="span6 offset3">
  	<h1><%= @user.name %></h1>
  	
<table class="profile" summary = "Profile information">
	<tr><%= gravatar_for @user %>  <%= @user.name %>
		<td class="main">
			
			
		</td>

	</tr>
</table> 